FROM node:22-alpine AS builder

ENV NODE_ENV=build

ARG UserID
RUN adduser -u $UserID -h /home/runner -D -s /bin/ash runner
USER $UserID
WORKDIR /home/runner

COPY ./package*.json /home/runner/
RUN npm ci

COPY ./src /home/runner/src
COPY ./test /home/runner/test
COPY ./tsconfig.json /home/runner/tsconfig.json
COPY ./.eslintrc.js /home/runner/.eslintrc.js
COPY ./.prettierrc /home/runner/.prettierrc

ENTRYPOINT [""]