FROM node:22-alpine AS builder

ENV NODE_ENV=build

#### AUTH TOKEN 
ARG NPM_ACCESS_TOKEN
ARG NPM_REGISTRY_EP
RUN npm config set @personal:registry 'https:${NPM_REGISTRY_EP}'
RUN npm config set -- '${NPM_REGISTRY_EP}:_authToken' '${NPM_ACCESS_TOKEN}'
RUN npm config set -- '//git.blvckleg.dev/api/v4/packages/npm/:_authToken' '${NPM_ACCESS_TOKEN}'
####

ARG UserID
RUN adduser -u $UserID -h /home/runner -D -s /bin/ash runner
USER $UserID
WORKDIR /home/runner

COPY ./package*.json /home/runner/
RUN npm ci

COPY ./src /home/runner/src
COPY ./test /home/runner/test
COPY ./tsconfig.json /home/runner/tsconfig.json
COPY ./.eslintrc.js /home/runner/.eslintrc.js
COPY ./.prettierrc /home/runner/.prettierrc

ENTRYPOINT [""]